# Generated by Django 5.2.13 on 2026-07-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.assessmentyear')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.organisation')),
            ],
        ),
    ]
