# Generated by Django 5.2.13 on 2026-07-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', '-id']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
