# Generated by Django 5.2.13 on 2026-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_event_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AGM', 'AGM'), ('SEMINAR', 'Seminar'), ('TRAINING', 'Training'), ('EXPO', 'Expo'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], default='AGM', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='gift_coupon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lucky_draw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
