# Generated by Django 5.2.13 on 2026-07-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_type_event_gift_coupon_event_lucky_draw_and_more'),
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('MEMBER', 'Member'), ('VISITOR', 'Visitor')], default='MEMBER', max_length=10)),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('coupon_issued', models.BooleanField(default=False)),
                ('attendance_status', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
