# Generated by Django 5.2.13 on 2026-07-25 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventattendance'),
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='attendance_status',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='visitor_name',
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='checkin_method',
            field=models.CharField(choices=[('QR', 'QR Scan'), ('MANUAL', 'Manual Entry'), ('ADMIN', 'Admin Entry')], default='QR', max_length=10),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='unique_member_attendance_per_event'),
        ),
    ]
