# Generated by Django 5.2.13 on 2026-07-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventattendance_attendance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='created_at',
        ),
    ]
