# Generated by Django 5.2.13 on 2026-07-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventattendance_created_at'),
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventattendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='events.event')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_visitors', to='membership.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
