# Generated by Django 5.2.13 on 2026-07-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('printed', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize_name', models.CharField(blank=True, max_length=200)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='events.eventattendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='events.event')),
            ],
            options={
                'ordering': ['coupon_no'],
            },
        ),
    ]
