# Generated by Django 5.2.13 on 2026-07-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventcoupon'),
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['prize_name'],
            },
        ),
        migrations.CreateModel(
            name='EventWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('CANCELLED', 'Cancelled')], default='PRESENT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='eventvisitor',
            constraint=models.UniqueConstraint(fields=('event', 'mobile'), name='unique_visitor_mobile_per_event'),
        ),
        migrations.AddField(
            model_name='eventprize',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventwinner',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='events.eventcoupon'),
        ),
        migrations.AddField(
            model_name='eventwinner',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventprize'),
        ),
    ]
