# Generated by Django 5.2.13 on 2026-07-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventprize_eventwinner_eventattendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoupon',
            name='lucky_draw_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcoupon',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_qr/'),
        ),
    ]
