# Generated by Django 5.2.13 on 2026-07-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventcoupon_lucky_draw_no_eventcoupon_qr_code'),
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisitor',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member'),
        ),
    ]
