# Generated by Django 5.2.13 on 2026-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventvisitor_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoupon',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventvisitor',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventvisitor',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
