# Generated by Django 5.2.13 on 2026-07-17 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation/logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.PositiveIntegerField(unique=True)),
                ('membership_no', models.CharField(max_length=50, unique=True)),
                ('joining_date', models.DateField()),
                ('membership_valid_upto', models.DateField()),
                ('membership_type', models.CharField(choices=[('REGULAR', 'Regular'), ('ASSOCIATE', 'Associate'), ('LIFE', 'Life Member'), ('HONORARY', 'Honorary')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('owner_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='members/photos/')),
                ('company_logo', models.ImageField(blank=True, upload_to='members/logo/')),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=30)),
                ('fssai_no', models.CharField(blank=True, max_length=30)),
                ('udyam_no', models.CharField(blank=True, max_length=30)),
                ('factory_license_no', models.CharField(blank=True, max_length=30)),
                ('do_license_no', models.CharField(blank=True, max_length=30)),
                ('trade_license_no', models.CharField(blank=True, max_length=30)),
                ('fire_noc_no', models.CharField(blank=True, max_length=30)),
                ('pollution_no', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.assessmentyear')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('GST', 'GST'), ('FSSAI', 'FSSAI'), ('UDYAM', 'UDYAM'), ('FACTORY', 'Factory License'), ('DO', 'DO License'), ('TRADE', 'Trade License'), ('FIRE', 'Fire NOC'), ('POLLUTION', 'Pollution Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='member_documents/')),
                ('remarks', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='membership.member')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentyear',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.organisation'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
