# Generated by Django 5.2.13 on 2026-07-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='validity_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessmentyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='assessment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.assessmentyear'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.organisation'),
        ),
    ]
