# Generated by Django 5.2.13 on 2026-07-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershiptype_description_membershiptype_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='validity_years',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='membership_category',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('LIFETIME', 'Lifetime')], default='ANNUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='assessment_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.assessmentyear'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
