# Generated by Django 5.2.13 on 2026-07-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_membershiptype_validity_years_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='membership_category',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershiptype'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
