# Generated by Django 5.2.13 on 2026-07-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_rename_membership_category_membershiptype_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('MEMBERSHIP', 'Membership Fee'), ('ADMISSION', 'Admission Fee'), ('RENEWAL', 'Renewal Fee'), ('IDCARD', 'Identity Card Fee'), ('LATE', 'Late Fee'), ('DONATION', 'Donation'), ('BUILDING', 'Building Fund'), ('WELFARE', 'Welfare Fund'), ('EVENT', 'Event Fee'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.organisation')),
            ],
            options={
                'ordering': ['fee_name'],
            },
        ),
    ]
