# Generated by Django 5.2.13 on 2026-07-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.PositiveIntegerField()),
                ('receipt_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.assessmentyear')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.organisation')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.paymentmode')),
            ],
            options={
                'ordering': ['-receipt_date', '-receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.feemaster')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='membership.receipt')),
            ],
        ),
    ]
