# Generated by Django 5.2.13 on 2026-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_receipt_receiptdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='members/qrcode/'),
        ),
    ]
