# Generated by Django 5.2.13 on 2026-07-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_memberrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrenewal',
            name='assessment_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='membership.assessmentyear'),
            preserve_default=False,
        ),
    ]
