# Generated by Django 5.2.13 on 2026-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_accountgroup_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='code_prefix',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
