# Generated by Django 5.2.13 on 2026-07-21 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_accountgroup_code_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['ledger_name']},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_code',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='opening_type',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_cash_or_bank',
            field=models.BooleanField(default=False, help_text='Tick for Cash/Bank ledgers only — drives auto Debit/Credit selection.'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('voucher_type', models.CharField(choices=[('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('JV', 'Journal Voucher'), ('CV', 'Contra Voucher')], max_length=2)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_narration', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='membership.voucher')),
            ],
        ),
    ]
