# Generated by Django 5.2.13 on 2026-07-21 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_ledger_options_remove_ledger_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['ledger_code']},
        ),
        migrations.AlterModelOptions(
            name='voucherentry',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_cash_or_bank',
        ),
        migrations.RemoveField(
            model_name='voucherentry',
            name='line_narration',
        ),
        migrations.AddField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='membership.accountgroup'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledger',
            name='opening_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10),
        ),
        migrations.AddField(
            model_name='ledger',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='narration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='voucherentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='voucherentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
