# Generated by Django 5.2.13 on 2026-07-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_alter_ledger_options_alter_voucherentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='entry_type',
            field=models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Dr', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='membership.accountgroup'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
