# Generated by Django 5.2.13 on 2026-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_voucherentry_entry_type_alter_ledger_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherentry',
            name='entry_type',
            field=models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Dr', max_length=2),
        ),
    ]
