# Generated by Django 5.2.13 on 2026-07-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_voucherentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemaster',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_masters', to='membership.ledger'),
        ),
    ]
