# Generated by Django 5.2.13 on 2026-07-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_feemaster_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_modes', to='membership.ledger'),
        ),
    ]
