# Generated by Django 5.2.13 on 2026-07-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_paymentmode_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='membership.ledger'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmode',
            unique_together={('organisation', 'name', 'ledger', 'description', 'is_active')},
        ),
    ]
