# Generated by Django 5.2.13 on 2026-07-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_member_ledger_alter_paymentmode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='membership.ledger'),
        ),
    ]
