# Generated by Django 5.2.13 on 2026-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_alter_member_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('MEMBERSHIP', 'Membership Fee'), ('ADMISSION', 'Admission Fee'), ('RENEWAL', 'Renewal Fee'), ('OTHER', 'Other Income')], default='MEMBERSHIP', max_length=50),
        ),
    ]
