# Generated by Django 5.2.13 on 2026-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_receipt_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='president_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secretary_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
