# Generated by Django 5.2.13 on 2026-07-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_organisation_president_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ledger',
        ),
    ]
